Object.assign(SECTIONS,{
c4:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 04</div><h1>Organizacion de Actividades Academicas</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.5</div></div>
<div class="grid-2"><div class="card"><h4><i class="fas fa-cogs"></i> Estructura Academica</h4><table class="tbl"><tr><td class="lb">Modalidad</td><td>100% Virtual: sincronica + asincronica</td></tr><tr><td class="lb">1 Credito</td><td>48 horas (16 acompanamiento + 32 autonomo)</td></tr><tr><td class="lb">Total Horas</td><td>6.912 horas academicas</td></tr><tr><td class="lb">Admision</td><td>Semestral</td></tr><tr><td class="lb">Modelo</td><td>Basado en competencias - enfoque constructivista</td></tr><tr><td class="lb">Estrategias</td><td>ABP, estudios de caso, simulacion, laboratorios virtuales</td></tr><tr><td class="lb">Evaluacion</td><td>Formativa y sumativa con rubricas estandarizadas</td></tr></table></div><div><div class="chart-box"><h4><i class="fas fa-clock"></i> Horas por Credito</h4><canvas id="horasChart" height="120"></canvas></div><div class="card" style="margin-top:12px"><h4><i class="fas fa-file-alt"></i> Documentos Soporte</h4><table class="tbl"><tr><td class="lb">Anexo 6</td><td>Modelo Pedagogico</td></tr><tr><td class="lb">Anexo 7</td><td>Politica Resultados de Aprendizaje</td></tr><tr><td class="lb">Anexo 8</td><td>Lineamiento de Educacion Virtual</td></tr><tr><td class="lb">Anexo 9</td><td>Lineamiento Educ. Virtual Institucional</td></tr><tr><td class="lb">Anexo 20</td><td>Lineamiento Virtualizacion Recursos</td></tr></table></div></div></div>`,

c5:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 05</div><h1>Investigacion e Innovacion</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.6</div></div>
<div class="timeline">
<div class="event-card type-legal">
    <span class="event-time">MARCO Y MODELO</span>
    <div class="event-title">Modelo de Investigacion, Innovacion y Desarrollo</div>
    <div class="event-desc">Fundamentado en la Politica Nacional de Ciencia, Tecnologia e Innovacion 2022-2031 (CONPES 4069 - DNP). Se orienta a la transferencia de conocimiento para resolver problemas reales del entorno, promoviendo la innovacion y el trabajo colaborativo en redes.</div>
    <div class="grid-2" style="margin-top:15px;">
        <button class="nav-btn" style="background:#111827; color:#fff; border:none; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_2_shape.png', 'Modelo de Investigacion, Innovacion y Desarrollo')"><i class="fas fa-sitemap" style="color:#FF6600;"></i> Ver Modelo de Investigacion</button>
        <button class="nav-btn" style="background:#111827; color:#fff; border:none; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_3_shape.png', 'Transferencia de Conocimiento')"><i class="fas fa-people-arrows" style="color:#FF6600;"></i> Ver Modelo de Transferencia</button>
    </div>
    <div style="margin-top:8px"><span class="tag-legal">Anexo 14 - Politica</span><span class="tag-legal">Anexo 15 - Lineamientos</span></div>
</div>

<div class="event-card type-academic">
    <span class="event-time">BASES EPISTEMOLOGICAS</span>
    <div class="event-title">Conceptualizacion Teorica del Programa</div>
    <div class="grid-2" style="margin-top:15px; margin-bottom:15px;">
        <button class="nav-btn" style="background:#111827; color:#fff; border:none; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_4_shape.png', 'Elementos para definir Lineas')"><i class="fas fa-layer-group" style="color:#00BFFF;"></i> Elementos de Definicion</button>
        <button class="nav-btn" style="background:#111827; color:#fff; border:none; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_5_shape.png', 'Conceptualizacion Teorica')"><i class="fas fa-brain" style="color:#00BFFF;"></i> Epistemologia del Programa</button>
    </div>
    <div class="grid-2" style="margin-top:8px">
        <div class="card-accent"><h4><i class="fas fa-microchip"></i> Revolucion 4.0</h4><p>Fundamentada en teorias de Klaus Schwab sobre la transformacion de los sistemas productivos con tecnologias avanzadas.</p></div>
        <div class="card"><h4><i class="fas fa-leaf"></i> Sostenibilidad</h4><p>Basado en autores como Bocken, Short, Rana y Evans, referente a practicas responsables en sectores productivos.</p></div>
        <div class="card"><h4><i class="fas fa-cogs"></i> Gestion Integral y Calidad</h4><p>Apoyado en teorias de J. Juran y A. Blanton Godfrey acerca de eficiencia operativa y competitividad global.</p></div>
        <div class="card"><h4><i class="fas fa-lightbulb"></i> Innovacion y Emprendimiento</h4><p>Basado en teorias de Schumpeter que conectan la creatividad y desarrollo tecnologico con el crecimiento economico.</p></div>
    </div>
</div>

<div class="event-card type-research">
    <span class="event-time">TENDENCIAS Y CAPACIDAD INSTALADA</span>
    <div class="event-title">Avances Institucionales (Grupos, Semilleros y Redes)</div>
    <div class="grid-4" style="display:grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-top:15px; margin-bottom:15px;">
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_6_shape.png', 'Tendencias del Conocimiento')"><i class="fas fa-chart-line text-green" style="color:#10B981;"></i> Tendencias</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_7_shape.png', 'Estrategias Institucionales')"><i class="fas fa-chess-knight text-green" style="color:#10B981;"></i> Estrategias</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_8_shape.png', 'Convocatorias y Redes')"><i class="fas fa-award text-green" style="color:#10B981;"></i> Convocatorias</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_9_shape.png', 'Semilleros')"><i class="fas fa-seedling text-green" style="color:#10B981;"></i> Semilleros</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_10_shape.png', 'Redes Proyectadas 1')"><i class="fas fa-project-diagram text-green" style="color:#10B981;"></i> Redes (1)</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_11_shape.png', 'Redes Proyectadas 2')"><i class="fas fa-globe text-green" style="color:#10B981;"></i> Redes (2)</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_12_shape.png', 'Grupo de Investigacion')"><i class="fas fa-users-cog text-green" style="color:#10B981;"></i> Grupo Inv.</button>
        <button class="nav-btn" style="background:#1f2937; color:#fff; border:1px solid #374151; padding:8px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_13_shape.png', 'Acciones Consolidadas')"><i class="fas fa-check-double text-green" style="color:#10B981;"></i> Acciones</button>
    </div>
    <table class="tbl">
        <thead><tr><th>Componente</th><th>Avance Institucional (Convocatoria MinCiencias)</th></tr></thead>
        <tbody>
            <tr><td class="lb">Categorizacion</td><td>Participacion activa en Convocatorias 894 de 2021 y 957 de 2024.</td></tr>
            <tr><td class="lb">Redes</td><td>Articulacion estrategica interinstitucional confirmada.</td></tr>
        </tbody>
    </table>
</div>

<div class="event-card type-induction">
    <span class="event-time">ESTRATEGIAS DEL PROGRAMA</span>
    <div class="event-title">Lineas Tematicas y Acciones Formativas</div>
    <div class="grid-3" style="margin-top:15px; margin-bottom:15px; gap:10px;">
        <button class="nav-btn" style="background:#111827; color:#fff; border:1px solid #FF6600; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_14_shape.png', 'Lineas de Investigacion')"><i class="fas fa-road" style="color:#FF6600;"></i> Lineas de Investigacion</button>
        <button class="nav-btn" style="background:#111827; color:#fff; border:1px solid #FF6600; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_16_shape.png', 'Estrategias Pedagogicas de Aula')"><i class="fas fa-chalkboard-teacher" style="color:#FF6600;"></i> Pedagogia de Aula</button>
        <button class="nav-btn" style="background:#111827; color:#fff; border:1px solid #FF6600; padding:10px; border-radius:5px; cursor:pointer;" onclick="openModal('assets/slide_18_shape.png', 'Aportes al Sector Productivo')"><i class="fas fa-industry" style="color:#FF6600;"></i> Aportes al Sector</button>
    </div>
    <div class="card" style="margin-bottom:15px; text-align:center;">
        <button class="nav-btn" style="background:#10B981; color:#fff; border:none; padding:12px 20px; font-weight:bold; border-radius:5px; cursor:pointer; width:100%; font-size:1.1em;" onclick="openModal('assets/slide_19_shape.png', 'Proyeccion de Investigacion a 7 Anos')"><i class="fas fa-calendar-alt"></i> Ver Plan de Desarrollo de Investigacion a 7 Anos</button>
    </div>
</div>
</div>`,

c6:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 06</div><h1>Relacion con el Sector Externo</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.7</div></div>
<div class="timeline"><div class="event-card type-induction"><span class="event-time">ESTRATEGIAS DE VINCULACION</span><div class="event-title">Mecanismos de Articulacion</div><div class="grid-3" style="margin-top:8px"><div class="card"><h4><i class="fas fa-building"></i> Convenios</h4><p>Visitas empresariales virtuales, pasantias y proyectos con sector productivo regional</p></div><div class="card-accent"><h4><i class="fas fa-globe"></i> Internacional</h4><p>Simposios virtuales con universidades aliadas y eventos academicos internacionales</p></div><div class="card"><h4><i class="fas fa-bullhorn"></i> Extension</h4><p>Congreso virtual interdisciplinar y foro anual de innovacion industrial</p></div></div></div>
<div class="event-card type-academic"><span class="event-time">PLAN OPERATIVO A 7 ANOS</span><div class="event-title">Hoja de Ruta de Relacionamiento</div><table class="tbl"><thead><tr><th>Ano</th><th>Accion Estrategica</th><th>Resultado Esperado</th></tr></thead><tbody><tr><td class="lb">1</td><td>Convenios marco con empresas regionales</td><td>5 convenios firmados</td></tr><tr><td class="lb">2</td><td>Visitas empresariales virtuales, semilleros con sector</td><td>10 visitas, 2 proyectos</td></tr><tr><td class="lb">3</td><td>Congreso virtual interdisciplinar nacional</td><td>100+ participantes</td></tr><tr><td class="lb">4</td><td>Simposio internacional con universidades aliadas</td><td>3 IES internacionales</td></tr><tr><td class="lb">5</td><td>Red de egresados, foro anual de innovacion</td><td>Red activa, 50+ egresados</td></tr><tr><td class="lb">6</td><td>Publicaciones conjuntas con sector productivo</td><td>3 publicaciones</td></tr><tr><td class="lb">7</td><td>Consolidacion de alianzas internacionales</td><td>5 alianzas permanentes</td></tr></tbody></table><div class="evidence-box"><i class="fas fa-handshake"></i>Lineamiento de Relacionamiento Externo (Anexo 16)</div></div></div>`,

c7:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 07</div><h1>Profesores</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.8</div></div>
<div class="grid-4"><div class="card" style="text-align:center"><div class="stat-num orange">8</div><div class="stat-label">Docentes</div></div><div class="card" style="text-align:center"><div class="stat-num">5 TC</div><div class="stat-label">Tiempo Completo</div></div><div class="card" style="text-align:center"><div class="stat-num orange">100%</div><div class="stat-label">Con Posgrado</div></div><div class="card" style="text-align:center"><div class="stat-num">17.5</div><div class="stat-label">Anos Exp. Promedio</div></div></div>
<div class="card" style="margin-top:16px"><h4><i class="fas fa-users"></i> Perfiles Docentes Completos</h4><table class="tbl"><thead><tr><th>Docente</th><th>Formacion Academica</th><th>Vinc.</th><th>Exp. Prof.</th><th>Exp. Doc.</th></tr></thead><tbody><tr><td>Fredy Castellanos B.</td><td>Mag. Prev. Riesgos Lab., Esp. Gerencia, Ing. Industrial</td><td>TC</td><td>25 anos</td><td>20 anos</td></tr><tr><td>Pedro E. Noriega G.</td><td>Curs. Doctorado, Esp. Salud Ocup., Ing. Industrial</td><td>TC</td><td>25 anos</td><td>20 anos</td></tr><tr><td>Guillermo Melendez</td><td>Curs. Doctorado, Maestria Riesgos, Abogado</td><td>TC</td><td>18 anos</td><td>15 anos</td></tr><tr><td>Andrea K. Hernandez</td><td>Mag. Administracion, Esp. BD, Ing. Industrial</td><td>TC</td><td>16 anos</td><td>14 anos</td></tr><tr><td>Cristian Perez Ch.</td><td>Cand. Mag. Gerencia, Esp. Finanzas, Adm. Empresas</td><td>TC</td><td>6 anos</td><td>1 ano</td></tr><tr><td>Ivan L. Mantilla J.</td><td>Mag. Innovacion Social, 3 Esp., Ing. Industrial</td><td>MT</td><td>12 anos</td><td>7 anos</td></tr><tr><td>Leonardo F. Perez V.</td><td>Master Finanzas, Mag. Direccion, Ing. Industrial</td><td>MT</td><td>15 anos</td><td>5 anos</td></tr><tr><td>Alejandro Almeyda C.</td><td>Mag. Gerencia, 2 Esp., Ing. de Mercados</td><td>MT</td><td>25 anos</td><td>23 anos</td></tr></tbody></table><div class="evidence-box"><i class="fas fa-id-badge"></i>Hojas de Vida (Anexo 19 y 20) | Estatuto Docente (Anexo 17)</div></div>
<div class="grid-2" style="margin-top:16px"><div class="chart-box"><h4><i class="fas fa-chart-bar"></i> Formacion Academica</h4><canvas id="formacionChart" height="160"></canvas></div><div class="chart-box"><h4><i class="fas fa-chart-line"></i> Proyeccion Docente a 7 Anos</h4><canvas id="proyeccionChart" height="160"></canvas></div></div>`,

c8:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 08</div><h1>Medios Educativos</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.9</div></div>
<div class="grid-3"><div class="card"><h4><i class="fas fa-desktop"></i> LMS Campus Virtual</h4><p>Plataforma de gestion del aprendizaje con recursos multimedia, foros, evaluaciones y seguimiento</p></div><div class="card-accent"><h4><i class="fas fa-book-reader"></i> Biblioteca E-Libro</h4><p>Contrato vigente con miles de titulos especializados en ingenieria y ciencias aplicadas</p></div><div class="card"><h4><i class="fas fa-video"></i> Plataforma Sincronica</h4><p>Encuentros en tiempo real con grabacion, chat y pizarra virtual</p></div><div class="card"><h4><i class="fas fa-shield-alt"></i> Software Antiplagio</h4><p>Verificacion de originalidad en trabajos academicos y tesis</p></div><div class="card"><h4><i class="fas fa-envelope"></i> Correo Institucional</h4><p>Suite de herramientas de productividad y comunicacion academica</p></div><div class="card"><h4><i class="fas fa-paint-brush"></i> Software Creacion</h4><p>Herramientas para produccion de contenidos digitales educativos</p></div></div>
<div class="timeline" style="margin-top:16px"><div class="event-card type-tech"><span class="event-time">ACCESIBILIDAD Y CAPACITACION</span><div class="event-title">Garantias de Calidad Digital</div><div class="grid-2" style="margin-top:8px"><div class="card"><h4>Capacitacion</h4><p>Formacion docente y estudiantil en uso de plataformas y herramientas TIC</p></div><div class="card"><h4>Soporte</h4><p>Mesa de ayuda disponible para estudiantes y docentes</p></div><div class="card"><h4>Accesibilidad</h4><p>Ajustes razonables para personas con necesidades especiales</p></div><div class="card"><h4>Actualizacion</h4><p>Plan de renovacion de licencias y plataformas a 7 anos</p></div></div><div style="margin-top:8px"><span class="tag-legal">Anexo 13 - Instructivo Campus</span><span class="tag-legal">Anexo 20 - Virtualizacion</span><span class="tag-legal">Anexo 21 - Contrato E-Libro</span></div></div></div>`,

c9:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Condicion 09</div><h1>Infraestructura Fisica y Tecnologica</h1></div><div class="date-badge">Art. 2.5.3.2.3.2.10</div></div>
<div class="grid-3"><div class="card-accent"><h4><i class="fas fa-building"></i> Sede A</h4><p>Oficinas administrativas y aulas. Contrato vigente. Uso de suelo y Licencia de Construccion aprobados.</p><div style="margin-top:6px"><span class="tag-legal" style="background:rgba(255,255,255,.2);color:#fff">Anexo 22</span><span class="tag-legal" style="background:rgba(255,255,255,.2);color:#fff">Anexo 23</span></div></div><div class="card"><h4><i class="fas fa-university"></i> Sede B</h4><p>Convenio institucional para espacios complementarios, bienestar universitario y extension.</p><div style="margin-top:6px"><span class="tag-legal">Anexo 25</span></div></div><div class="card"><h4><i class="fas fa-microscope"></i> Sede C</h4><p>Laboratorios especializados, salas de computo y espacios de practica. Contrato vigente.</p><div style="margin-top:6px"><span class="tag-legal">Anexo 24</span></div></div></div>
<div class="grid-2" style="margin-top:16px"><div class="card"><h4><i class="fas fa-server"></i> Plataforma Tecnologica</h4><table class="tbl"><tr><td class="lb">LMS</td><td>Gestion del aprendizaje institucional</td></tr><tr><td class="lb">Sincronico</td><td>Videoconferencias y clases en vivo</td></tr><tr><td class="lb">E-Libro</td><td>Acceso a miles de titulos especializados</td></tr><tr><td class="lb">Antiplagio</td><td>Verificacion de originalidad</td></tr><tr><td class="lb">Correo</td><td>Suite de productividad</td></tr><tr><td class="lb">Servidores</td><td>Capacidad para 140+ estudiantes/cohorte</td></tr></table></div><div class="chart-box"><h4><i class="fas fa-chart-bar"></i> Dimensionamiento Tecnologico</h4><canvas id="techChart" height="180"></canvas></div></div>`,

normativo:`<div class="slide-header"><div class="slide-title"><div class="slide-subtitle">Soporte Documental</div><h1>Marco Normativo y Anexos</h1></div></div>
<div class="grid-2"><div class="card"><h4><i class="fas fa-folder-open"></i> Documentos del Programa</h4><table class="tbl"><tr><td class="lb">Anexo 1</td><td>Acuerdo de Creacion del Programa</td></tr><tr><td class="lb">Anexo 2</td><td>Acuerdo de Aprobacion</td></tr><tr><td class="lb">Anexo 3</td><td>Documento Maestro del Programa</td></tr><tr><td class="lb">Anexo 4</td><td>Estudio de Pertinencia</td></tr><tr><td class="lb">Anexo 5</td><td>Proyecto Educativo Institucional (PEI)</td></tr><tr><td class="lb">Anexo 6</td><td>Modelo Pedagogico</td></tr><tr><td class="lb">Anexo 7</td><td>Politica Resultados de Aprendizaje / Plan Vinc. Docente</td></tr><tr><td class="lb">Anexo 8-9</td><td>Lineamientos Educacion Virtual</td></tr><tr><td class="lb">Anexo 10</td><td>Reglamento Estudiantil</td></tr><tr><td class="lb">Anexo 11</td><td>Syllabus del Programa</td></tr><tr><td class="lb">Anexo 12</td><td>Reglamento Opcion de Grado</td></tr><tr><td class="lb">Anexo 13</td><td>Instructivo Campus Virtual</td></tr></table></div>
<div class="card"><h4><i class="fas fa-archive"></i> Evidencias y Soportes</h4><table class="tbl"><tr><td class="lb">Anexo 14</td><td>Politica de Investigacion Institucional</td></tr><tr><td class="lb">Anexo 15</td><td>Lineamientos Generales de Investigacion</td></tr><tr><td class="lb">Anexo 16</td><td>Lineamiento Relacionamiento Externo</td></tr><tr><td class="lb">Anexo 17</td><td>Estatuto Docente</td></tr><tr><td class="lb">Anexo 18</td><td>Lineamiento Distribucion Planes de Trabajo</td></tr><tr><td class="lb">Anexo 19-20</td><td>Hojas de Vida Docentes</td></tr><tr><td class="lb">Anexo 21</td><td>Contrato Biblioteca E-Libro</td></tr><tr><td class="lb">Anexo 22</td><td>Contrato Sede A</td></tr><tr><td class="lb">Anexo 23</td><td>Uso de Suelo y Licencia de Construccion</td></tr><tr><td class="lb">Anexo 24</td><td>Contrato Sede C</td></tr><tr><td class="lb">Anexo 25</td><td>Convenio Sede B</td></tr></table></div></div>
<div class="event-card type-sst" style="margin-top:16px;margin-left:0"><span class="event-time">CONCLUSION</span><div class="event-title">9 Condiciones de Calidad Sustentadas</div><div class="event-desc">El programa de Ingenieria Industrial de la Corporacion Escuela Tecnologica del Oriente cumple con rigor cada condicion del Decreto 1330 de 2019. 25 anexos verificables soportan la propuesta academica.</div><div class="evidence-box"><i class="fas fa-check-double"></i>Programa pertinente, innovador y alineado con la Industria 4.0. Estamos a disposicion para cualquier ampliacion.</div></div>`
});
