const LOGO='https://campusvirtual.tecnologicadeloriente.edu.co/pluginfile.php/1/theme_edmo/mobile_logo/1772556380/logo%2Bvertical-1920w.jpg';
const L=`<img src="${LOGO}" class="logo-fixed" alt="ETO">`;
const slides=[
// 0 PORTADA
`<div class="hero-slide">${L}<p class="label-vig">VIGILADO MINEDUCACION</p><h1>INGENIERIA <span class="accent">INDUSTRIAL</span></h1><p style="font-size:20px;margin-top:16px">Sustentacion de Condiciones de Calidad para Registro Calificado</p><div class="line-accent thick"></div><p style="font-size:14px;color:#555">Decreto 1330 de 2019 · Modalidad Virtual · 144 Creditos · 8 Semestres</p><div class="circle-deco large"></div></div>`,
// 1 AGENDA
`${L}<p class="cond-badge">Hoja de Ruta - 2 Dias de Sustentacion</p><h2>CONDICIONES DE <span class="accent">CALIDAD</span></h2><div class="line-accent"></div><div class="data-grid" style="margin-top:20px"><div class="data-cell"><h4>01</h4><p>Denominacion</p></div><div class="data-cell"><h4>02</h4><p>Justificacion</p></div><div class="data-cell accent-cell"><h4>03</h4><p>Contenidos Curriculares</p></div><div class="data-cell"><h4>04</h4><p>Org. Actividades</p></div><div class="data-cell"><h4>05</h4><p>Investigacion</p></div><div class="data-cell"><h4>06</h4><p>Sector Externo</p></div><div class="data-cell"><h4>07</h4><p>Profesores</p></div><div class="data-cell"><h4>08</h4><p>Medios Educativos</p></div><div class="data-cell"><h4>09</h4><p>Infraestructura</p></div></div>`,
// 2 FICHA TECNICA
`${L}<p class="cond-badge">Informacion General</p><h2>FICHA <span class="accent">TECNICA</span></h2><div class="line-accent"></div><div class="two-col" style="margin-top:16px"><div><table class="clean-table"><tr><td class="lb">Programa</td><td>Ingenieria Industrial</td></tr><tr><td class="lb">Titulo</td><td>Ingeniero Industrial</td></tr><tr><td class="lb">Nivel</td><td>Pregrado Universitario</td></tr><tr><td class="lb">Modalidad</td><td>Virtual</td></tr><tr><td class="lb">Creditos</td><td>144</td></tr><tr><td class="lb">Duracion</td><td>8 Semestres</td></tr><tr><td class="lb">Admision</td><td>Semestral</td></tr><tr><td class="lb">Estudiantes 1er Sem</td><td>140</td></tr></table></div><div><table class="clean-table"><tr><td class="lb">Matricula</td><td>$4.200.000</td></tr><tr><td class="lb">NBC</td><td>Ingenieria Industrial y afines</td></tr><tr><td class="lb">Campo Amplio</td><td>Ingenieria, Industria y Construccion</td></tr><tr><td class="lb">Campo Especifico</td><td>Ingenieria y profesiones afines</td></tr><tr><td class="lb">Area Conocimiento</td><td>Ing., Arquitectura, Urbanismo</td></tr><tr><td class="lb">Escuela</td><td>Escuela de Ingenierias</td></tr><tr><td class="lb">Norma Creacion</td><td>Acuerdo 011/2024</td></tr><tr><td class="lb">Norma Aprobacion</td><td>Acuerdo 021, Acuerdo 03/2026</td></tr></table></div></div>`,
// 3 COND 1 DENOMINACION - Marco Legal
`${L}<p class="cond-badge">Condicion 01 - Denominacion</p><h2>MARCO <span class="accent">LEGAL</span></h2><div class="line-accent"></div><div class="two-col" style="margin-top:16px"><div><ul class="feat-list"><li>Ley 30 de 1992 - Organizacion del servicio publico de Educacion Superior</li><li>Ley 115 de 1994 - Ley General de Educacion</li><li>Ley 842 de 2003 - Ley de los Ingenieros, regula ejercicio profesional</li><li>Ley 1188 de 2008 - Regula el Registro Calificado</li><li>Ley 1740 de 2014 - Inspeccion y vigilancia de Educacion Superior</li><li>Decreto 1330 de 2019 - Condiciones de calidad para Registro Calificado</li><li>Resolucion 021795 de 2020 - Parametros de autoevaluacion</li></ul></div><div><div class="stat-block"><div class="stat-number orange">2024</div><div class="stat-desc">Ano de creacion del programa - Acuerdo 011</div></div><div class="stat-block" style="margin-top:20px"><div class="stat-number">2026</div><div class="stat-desc">Acuerdo 03 - Aprobacion presentacion ante MEN</div></div><div class="stat-block" style="margin-top:20px"><div class="stat-number orange">ETO</div><div class="stat-desc">Institucion Universitaria / Escuela Tecnologica</div></div></div></div>`,
// 4 COND 1 DENOMINACION - Clasificacion
`${L}<p class="cond-badge">Condicion 01 - Denominacion</p><h2>CLASIFICACION <span class="accent">CINE / SNIES</span></h2><div class="line-accent"></div><div class="two-col" style="margin-top:16px"><div><table class="clean-table"><thead><tr><th>Nivel</th><th>Clasificacion</th></tr></thead><tbody><tr><td class="lb">Campo Amplio</td><td>Ingenieria, Industria y Construccion</td></tr><tr><td class="lb">Campo Especifico</td><td>Ingenieria y profesiones afines</td></tr><tr><td class="lb">Campo Detallado</td><td>Ingenieria y profesiones afines no clasificadas en otra parte</td></tr><tr><td class="lb">Area de Conocimiento</td><td>Ingenieria, arquitectura, urbanismo y afines</td></tr><tr class="row-accent"><td class="lb">NBC</td><td>Ingenieria Industrial y afines</td></tr></tbody></table></div><div><p style="font-size:15px;line-height:1.7">La denominacion del programa refleja de manera clara el campo del conocimiento de la Ingenieria Industrial. El enfoque en transformacion digital incluye procesos de automatizacion, inteligencia artificial, analisis de big data e ingenieria 4.0.</p><p style="font-size:15px;line-height:1.7;margin-top:12px">La modalidad virtual responde a la creciente demanda de educacion accesible, flexible y respaldada por tecnologias de vanguardia.</p></div></div>`,
// 5 COND 1 DENOMINACION - Comparativo
`${L}<p class="cond-badge">Condicion 01 - Denominacion</p><h2>PERTINENCIA <span class="accent">NACIONAL</span></h2><div class="line-accent"></div><p style="font-size:14px;margin:8px 0">Analisis comparativo con programas homologos en modalidad virtual registrados en SNIES</p><table class="clean-table" style="margin-top:8px"><thead><tr><th>IES</th><th>Enfoque Diferenciador del Perfil</th></tr></thead><tbody><tr><td>U. de Manizales</td><td>Transformacion digital, diseno de procesos sostenibles, inteligencia de negocios</td></tr><tr><td>U. Piloto</td><td>Modelar, gestionar y mejorar sistemas organizacionales generando valor</td></tr><tr><td>UCC</td><td>Liderazgo estrategico, optimizacion de procesos, adaptabilidad tecnologica</td></tr><tr><td>UNAD</td><td>Operaciones y manufactura, logistica, gestion de proyectos, innovacion</td></tr><tr><td>Pol. Grancolombiano</td><td>Diseno creativo e innovador, optimizacion, metodo cientifico</td></tr><tr><td>Areandina</td><td>Industria 4.0, Big Data, simulacion, IoT, aprendizaje autonomo</td></tr><tr><td>UNIMINUTO</td><td>Sistemas productivos flexibles, formulacion de proyectos, productividad</td></tr><tr><td>Iberoamericana</td><td>Analitica de datos, modelamiento organizacional, diagnostico empresarial</td></tr><tr class="row-accent"><td>ETO (Nuestro)</td><td>IA transversal en curriculo, Industria 4.0, sostenibilidad integrada, Big Data</td></tr></tbody></table>`,
// 6 COND 1 - Correlacion Denominacion
`${L}<p class="cond-badge">Condicion 01 - Denominacion</p><h2>CORRELACION CON EL <span class="accent">CURRICULO</span></h2><div class="line-accent"></div><p style="font-size:14px;margin:8px 0">Como los contenidos curriculares responden directamente a la denominacion del programa</p><table class="clean-table" style="margin-top:8px"><thead><tr><th>Elemento del Perfil</th><th>Asignaturas del Plan de Estudios</th><th>Justificacion</th></tr></thead><tbody><tr><td>Diseno y optimizacion de procesos</td><td>Procesos Industriales, Distribucion de Planta, IO I y II, Gestion de Operaciones con IA</td><td>Herramientas para analizar, modelar y mejorar sistemas productivos</td></tr><tr><td>Gestion tecnologica y toma de decisiones</td><td>Big Data y Analitica, IA, Modelacion y Simulacion con IA</td><td>Competencias para aplicar tecnologias avanzadas en decisiones estrategicas</td></tr><tr><td>Sostenibilidad y responsabilidad social</td><td>Desarrollo Sostenible, Gestion de Proyectos Sostenibles, Bioetica</td><td>Soluciones industriales que responden a desafios sociales y ambientales</td></tr><tr><td>Gestion de talento humano</td><td>Gerencia del TH, Teoria Organizacional, Derecho Laboral</td><td>Liderazgo, motivacion y normatividad para optimizar desempeno</td></tr><tr><td>Innovacion y emprendimiento</td><td>Lab. Innovacion, Formulacion y Evaluacion de Proyectos</td><td>Pensamiento creativo y capacidad para liderar proyectos innovadores</td></tr><tr><td>Bases de ingenieria</td><td>Matematicas, Fisica I y II, Algebra, Calculo, Termodinamica</td><td>Base tecnica para comprender y resolver problemas de ingenieria</td></tr></tbody></table>`,
// 7 COND 2 JUSTIFICACION - Contexto
`${L}<p class="cond-badge">Condicion 02 - Justificacion</p><h2>CONTEXTO Y <span class="accent">PERTINENCIA</span></h2><div class="line-accent"></div><div class="two-col" style="margin-top:16px"><div><p style="font-size:15px;line-height:1.7">El programa se configura como una propuesta curricular coherente, pertinente e innovadora, cuyo diseno responde de manera articulada a las exigencias de la Revolucion 4.0, integrando competencias tecnicas en ingenieria con el dominio de herramientas emergentes como la inteligencia artificial, el big data y la simulacion de procesos.</p><p style="font-size:15px;line-height:1.7;margin-top:12px">Esta articulacion atraviesa de manera transversal los objetivos formativos, los contenidos curriculares, el perfil del egresado y los valores diferenciales del programa.</p><div class="line-accent" style="margin-top:20px"></div><p style="font-size:13px;color:#555">Fuente: Documento Maestro del Programa - Condicion 2</p></div><div><div class="data-grid" style="grid-template-columns:1fr"><div class="data-cell accent-cell"><h4>Revolucion 4.0</h4><p>IA, Big Data, Simulacion y Automatizacion como ejes de transformacion empresarial colombiana</p></div><div class="data-cell"><h4>ODS Alineados</h4><p>Contribucion directa a ODS 4 (Educacion), 8 (Trabajo), 9 (Industria), 11 (Ciudades), 12 (Produccion Responsable)</p></div><div class="data-cell"><h4>Brecha Regional</h4><p>Baja oferta virtual de calidad en Santander para ingenieria industrial con enfoque 4.0</p></div></div></div></div>`,
// 8 COND 2 - Diferenciadores
`${L}<p class="cond-badge">Condicion 02 - Justificacion</p><h2>VALOR <span class="accent">DIFERENCIAL</span></h2><div class="line-accent"></div><div class="stats-row"><div class="stat-block"><div class="stat-number orange">6</div><div class="stat-desc">Asignaturas con IA integrada</div></div><div class="stat-block"><div class="stat-number">3</div><div class="stat-desc">Ejes estrategicos transversales</div></div><div class="stat-block"><div class="stat-number orange">4.0</div><div class="stat-desc">Enfoque Industria</div></div><div class="stat-block"><div class="stat-number">100%</div><div class="stat-desc">Virtual con calidad</div></div></div><div class="two-col" style="margin-top:20px"><div><h3 style="font-size:18px">INTEGRACION <span class="accent">TECNOLOGICA</span></h3><ul class="feat-list"><li>Gestion de Operaciones con IA - aplicacion directa en produccion</li><li>Produccion e IA - automatizacion inteligente de lineas</li><li>Modelacion y Simulacion con IA - gemelos digitales</li><li>Big Data y Analitica de Datos - decisiones basadas en datos</li><li>Inteligencia Artificial - fundamentos y aplicaciones</li><li>Competencias Digitales - alfabetizacion tecnologica</li></ul></div><div><h3 style="font-size:18px">EJES <span class="accent">ESTRATEGICOS</span></h3><ul class="feat-list"><li>Sostenibilidad: Desarrollo Sostenible, Gestion Proyectos Sostenibles, Bioetica</li><li>Innovacion: Laboratorio de Innovacion, Pensamiento Estrategico y Prospectivo</li><li>Gestion: Gerencia Tecnologica, Diagnostico Empresarial, Formulacion Proyectos</li></ul></div></div>`,
// 9 COND 2 - Oferta y Demanda
`${L}<p class="cond-badge">Condicion 02 - Justificacion</p><h2>OFERTA Y <span class="accent">DEMANDA</span></h2><div class="line-accent"></div><div class="two-col" style="margin-top:16px"><div><h3 style="font-size:18px">DISTRIBUCION <span class="accent">GEOGRAFICA</span></h3><p style="font-size:14px;margin:8px 0">Concentracion de la oferta en modalidad virtual por municipio (SNIES 2024)</p><table class="clean-table"><thead><tr><th>Ciudad</th><th>IES con programa</th></tr></thead><tbody><tr><td>Bogota</td><td>UNAD, Piloto, Iberoamericana, UNIMINUTO</td></tr><tr><td>Medellin</td><td>UCC</td></tr><tr><td>Barranquilla</td><td>Areandina</td></tr><tr><td>Cali</td><td>UAO</td></tr><tr><td>Manizales</td><td>U. de Manizales</td></tr><tr class="row-accent"><td>Bucaramanga / Santander</td><td>ETO - Oportunidad unica</td></tr></tbody></table></div><div><h3 style="font-size:18px">ARTICULATION CON <span class="accent">COMPETENCIAS</span></h3><p style="font-size:14px;line-height:1.6;margin:8px 0">La propuesta curricular garantiza el desarrollo de competencias especificas en ingenieria y habilidades tecnologicas avanzadas esenciales para el entorno industrial actual.</p><p style="font-size:14px;line-height:1.6">La inclusion de asignaturas como Gestion de Operaciones con IA y Produccion e IA permite aplicar soluciones inteligentes a problemas reales, mejorando la productividad y eficiencia organizacional.</p><div class="line-accent" style="margin-top:16px"></div><canvas id="demandaChart" height="160"></canvas></div></div>`,
];
function renderSlides(){const c=document.querySelector('.slides');slides.forEach(s=>{const sec=document.createElement('section');sec.innerHTML=s;c.appendChild(sec);});}
document.addEventListener('DOMContentLoaded',()=>{renderSlides();Reveal.initialize({hash:true,transition:'slide',width:1280,height:720,margin:0.04,controls:true,progress:true,center:true,slideNumber:'c/t'});Reveal.on('slidechanged',initCharts);Reveal.on('ready',initCharts);});
let ci={};
function initCharts(){
const d=document.getElementById('demandaChart');
if(d&&!ci.d){ci.d=new Chart(d,{type:'bar',data:{labels:['Bogota','Medellin','B/quilla','Cali','Manizales','B/manga'],datasets:[{label:'Programas',data:[4,1,1,1,1,0],backgroundColor:['#000','#000','#000','#000','#000','#FF4500'],borderRadius:0}]},options:{responsive:true,plugins:{legend:{display:false}},scales:{y:{beginAtZero:true,ticks:{color:'#000',stepSize:1}},x:{ticks:{color:'#000',font:{size:11}}}}}});}
}
